os:
  - linux
  - osx
  - windows

language: cpp
compiler:
  - gcc
  - clang
install: make deps > /dev/null
script: make app
branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install lcov libxss-dev build-essential libgl-dev libreadline-dev libssl-dev libqt5designer5 qttools5-dev qtbase5-private-dev; fi
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10.
