os:
  - osx

language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always
install: make deps > /dev/null
script: make app_release
osx_image: xcode10.1
