os:
  - windows

language: csharp
compiler:
  - gcc
  - clang

branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always

solution: src/ui/windows/TogglDesktop/TogglDesktop.sln
script:
- xbuild src/ui/windows/TogglDesktop/TogglDesktop.sln
