os:
  - linux
  - osx
  - windows

language: cpp
compiler:
  - gcc
  - clang
install: make deps > /dev/null
script: make app
branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    packages:
      - lcov
      - libxss-dev
      - build-essential
      - libgl-dev
      - libreadline-dev
      - libssl-dev
      - libqt5designer5
      - qttools5-dev
      - qtbase5-private-dev

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
