os:
  - windows

language: csharp
compiler:
  - gcc
  - clang

branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always
mono: none
dotnet: 2.1
solution: src/ui/windows/TogglDesktop/TogglDesktop.sln
script:
- msbuild src/ui/windows/TogglDesktop/TogglDesktop.sln /p:Configuration=Release /t:TogglDesktop:Clean
