os:
  - linux
  - osx
  - windows

language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    packages:
      - lcov
      - libxss-dev
      - build-essential
      - libreadline-dev
      - libssl-dev
      - libqt5designer5
      - qttools5-dev
      - qtbase5-private-dev

matrix:
  include:
    - os: linux
      script: make app
      dist: xenial
    - os: osx
      install: make deps > /dev/null
      script: make app_release
      osx_image: xcode10.1
    - os: windows
      solution: src/ui/windows/TogglDesktop/TogglDesktop.sln /p:Configuration=Release /t:TogglDesktop:Clean
