os:
  - linux

language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master
notifications:
  recipients:
    - indzuliin@gmail.com
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    packages:
      - lcov
      - libxss-dev
      - build-essential
      - libreadline-dev
      - libssl-dev
      - libqt5designer5
      - qttools5-dev
      - qtbase5-private-dev
script: 
  - exportCMAKE_PREFIX_PATH="$HOME/Qt/latest/gcc_64/lib/cmake/"
  - make app
dist: xenial
